### ISSUE TITLE
Cannot read property 'r' of undefined

### ISSUE THREAD

**Issue by fireside68** [indutny/elliptic#234]
I am following a tutorial based on building a blockchain and, ultimately, a cryptocurrency, called "Build a Blockchain and Cryptocurrency from Scratch" (available on Udemy; highly recommend). We've reached a point where tests are written to validate a valid transaction. The tests fail, returning:

`TypeError: Cannot read property 'r' of undefined`

The stack trace first points to this line in my code, with the carat pointing at the `verify` portion (visible [here](https://github.com/fireside68/sf-chain/blob/2cdd2006ea7333253be18fad2bd36fbb1b506eb6/chain-util.js#L20)):

`return ec.keyFromPublic(publicKey, 'hex').verify(dataHash, signature)`

The stack trace itself:

`    at new Signature (node_modules/elliptic/lib/elliptic/ec/signature.js:15:18)

      at EC.verify (node_modules/elliptic/lib/elliptic/ec/index.js:158:15)

      at KeyPair.verify (node_modules/elliptic/lib/elliptic/ec/key.js:112:18)

      at Function.verifySignature (chain-util.js:20:51)

      at Function.verifyTransaction (wallet/transaction.js:36:26)

      at Object.<anonymous> (wallet/transaction.test.js:30:28)`

I was able to verify that my code is, at this point in the tutorial, the same as his. Because it's a purchased tutorial, I find it to be a bit unethical to link directly to the Github repository containing that code.

**Comment by fireside68** [comment]
UPDATE: I found the issue. 

I was missing the input for the `transaction` object. The `input` is where the `address` and `signature` live. Making this change got my tests to pass.
